#include QMK_KEYBOARD_H

void send_alt_code_P(const uint16_t str) {
    SEND_STRING(SS_DOWN(X_RALT));
    register_code16(str);
    unregister_code16(str);
    SEND_STRING(SS_UP(X_RALT));
//    wait_ms(15); // seems to be necessary when sending two alt-codes one next to the other. 9ms was sufficient on my system
}

#define SEND_ALT_CODE(string) send_alt_code_P(string)

enum custom_keycodes {
    QMKBEST = SAFE_RANGE,
    QMKURL,
    ARING,
    OUML,
    AUML,
    EHAT
    // AHAT,
    // EHAT,
    // IHAT,
    // OHAT,
    // UHAT,
    // UEYES,
    // NHAT,
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case EHAT:
            if (record->event.pressed) {
                send_alt_code_P(KC_G);
            }
            break;
        case ARING:
            if (record->event.pressed) {
                send_alt_code_P(KC_W);
            }
            break;
        case OUML:
            if (record->event.pressed) {
                send_alt_code_P(KC_O);
            }
            break;
        case AUML:
            if (record->event.pressed) {
                send_alt_code_P(KC_A);
            }
            break;
    }
    return true;
}

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_GRV, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLSH, KC_TAB, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_RSFT, KC_LSFT, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_LBRC, KC_RBRC, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_RCTL, KC_LCTL, KC_LALT, MO(1), KC_SPC, KC_ENT, MO(2), KC_BSPC, KC_LGUI),
	[1] = LAYOUT(XXXXXXX, TO(4), TO(5), XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TILD, _______, KC_UNDO, KC_CUT, KC_COPY, KC_PSTE, KC_FIND, _______, _______, XXXXXXX, KC_UNDS, KC_EQL, KC_PLUS, KC_SLSH, KC_BSLS, _______, _______, _______, _______, _______, MO(3), _______, _______),
	[2] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NUM, KC_HOME, KC_UP, KC_PGUP, KC_PAST, KC_PSLS, KC_CAPS, ARING, OUML, AUML, EHAT, KC_PGUP, KC_CAPS, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PPLS, KC_PMNS, _______, KC_DEL, KC_INS, KC_HOME, KC_END, KC_PGDN, _______, KC_PSCR, KC_P0, KC_END, KC_DOWN, KC_PGDN, KC_PDOT, KC_PEQL, _______, _______, MO(3), _______, _______, _______, _______, _______),
	[3] = LAYOUT(XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, BL_UP, XXXXXXX, KC_NUM, KC_P7, KC_P8, KC_P9, KC_PAST, XXXXXXX, KC_VOLU, BL_TOGG, BL_STEP, BL_BRTG, BL_DOWN, XXXXXXX, KC_CAPS, KC_P4, KC_P5, KC_P6, KC_PPLS, XXXXXXX, KC_VOLD, RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, XXXXXXX, KC_P0, KC_P1, KC_P2, KC_P3, KC_PDOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, _______, _______, _______, _______, _______, _______, _______, _______),
	[4] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_GRV, KC_F5, KC_H, KC_Q, KC_W, KC_E, KC_R, KC_Y, KC_K, KC_UP, KC_L, KC_U, KC_EQL, KC_TAB, KC_J, KC_A, KC_S, KC_D, KC_F, KC_N, KC_LEFT, KC_DOWN, KC_RGHT, KC_SCLN, KC_NUHS, KC_LSFT, KC_Z, KC_O, KC_M, KC_I, KC_P, KC_B, KC_T, KC_G, KC_X, KC_C, KC_V, KC_COMM, KC_DOT, KC_LCTL, KC_LALT, MO(6), KC_SPC, KC_ENT, XXXXXXX, KC_BSPC, KC_GRV),
	[5] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_GRV, KC_TAB, KC_Q, KC_W, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_DEL, KC_INS, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_INT1, KC_LALT, KC_LGUI, MO(6), KC_SPC, KC_ENT, KC_RALT, KC_RCTL, KC_RSFT),
	[6] = LAYOUT(TO(0), KC_F1, KC_F2, KC_F3, KC_F4, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, _______, KC_Y, KC_K, KC_UP, KC_L, KC_U, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, KC_N, KC_LEFT, KC_DOWN, KC_RGHT, KC_SCLN, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, KC_G, KC_X, KC_C, KC_V, KC_COMM, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




